class_names = [
    "Qaitbay Castle",
    "Muizz Street",
    "Mosque_of_al-Mahmudiya",
    "Statue of Tutankhamun with Ankhesenamun",
    "11_King_Thutmose_III",
    "Alexandria_Opera_House",
    "Tomb_of_Unknown_Soldier_in_Cairo",
    "Azhar Mosque",
    "Hanging_Church_(Cairo)",
    "Mosque_of_Qanibay_al-Rammah",
    "Ramses II Red Granite Statue",
    "Abu_Haggag_Mosque",
    "Al-Aqmar_Mosque",
    "Mosque_of_Saint_Ibrahim_El-Desouky",
    "Speos_Artemidos",
    "16_Nazlet_Khater_Skeleton",
    "Bab_Zuwayla",
    "30_Muhammad_Ali_Pasha",
    "Al-Shate'e_Mosque",
    "31_Puplit _of_the_Mosque_of_Abu_Bakr_bin_Mazhar",
    "Colossi_of_Memnon",
    "Agiba_beach",
    "Al-Manyal_Palace_Museum",
    "Qubbet_el-Hawa",
    "Monastery_of_Saint_Anthony",
    "Abdeen_Palace",
    "Egyptian_Geological_Museum",
    "Deir_el-Medina",
    "Kiosk_of_Qertassi",
    "Pyramid_of_Djoser",
    "10_The_HolyQuran",
    "Mosque-Madrassa_of_Sultan_Hassan",
    "Hatshepsut face",
    "Pyramid_of_Amenemhat_III_in_Hawara",
    "33_The_Madrasaa_and_Mosque_of_Sultan_Hassan",
    "Monastery_of_Saint_Bishoy",
    "Amr Ibn Al-Aas Mosque",
    "Hanging church",
    "Monastery_of_Saint_Simeon_in_Aswan",
    "Al-Ghuri_Complex",
    "Bab_al-Nasr_(Cairo)",
    "Gebel_el-Silsila",
    "Valley_of_the_Queens",
    "Na'ama_Bay",
    "Tomb_of_Nakht_TT52",
    "Kitchener's_Island",
    "amenhotep iii and tiye",
    "4_Royal_Statues",
    "Temple_of_Isis_in_Philae",
    "Muizz_Street",
    "Karnak_precinct_of_Amun-Ra",
    "Pyramid_of_Djedefra",
    "Montaza_Palace",
    "Hatshepsut Statue",
    "29_Model_of_building",
    "El_Alamein_Military_Museum",
    "34_Wekalet_al-Ghouri",
    "El-Bahr_mosque,_Dumyat",
    "Deir_el-Muharraq",
    "Soma_Bay",
    "Suez_Canal_Bridge",
    "Great Pyramids of Giza",
    "Colossal Statue of Ramesses II",
    "Mausoleum_of_Aga_Khan",
    "Bayt_Al-Suhaymi",
    "Egyptian_Museum_(Cairo)",
    "Mortuary_Temple_of_Seti_I_in_Qurna",
    "Pyramid_of_Djedkare_Isesi",
    "Goddess Isis with her child",
    "Qasr_al-Nil_Bridge",
    "Aqsunqur_Mosque",
    "Bab_al-Futuh",
    "Madrasah_of_Sarghatmish",
    "40_Mashrabiya",
    "48_Stela_of_King_Qaa",
    "Wadi_Degla",
    "41_Astrolabe",
    "Bent_Pyramid",
    "Aswan_Botanical_Garden",
    "Mask of Tutankhamun",
    "47_Ottoman_Period_Carpet",
    "28_Mohamed_Talaat_Pasha_Harb",
    "Bibliotheca_Alexandrina_planetarium",
    "Wadi_el-Raiyan",
    "43_The_Protective_Goddesses",
    "Babylon Fortress",
    "Pyramid_of_Unas",
    "Edfu_Temple",
    "25_Mahalawi_water_ewers",
    "Grand_Egyptian_Museum",
    "Pyramid_of_Sahure",
    "Temple_of_Kom_Ombo",
    "Ben_Ezra_Synagogue",
    "Al-Salih_Tala'i_Mosque",
    "Ptolemaic_Temple_of_Hathor_in_Deir_el-Medina",
    "Theban_Necropolis",
    "Nefertiti",
    "Monastery_of_Saint_Macarius_the_Great",
    "Great_Sphinx_of_Giza",
    "Pyramid_of_Senusret_II",
    "Unfinished_obelisk_in_Aswan",
    "Fatimid_Cemetery_in_Aswan",
    "Temple_of_Hibis",
    "Alhakim biAmr Allah",
    "Al-Azhar_Park_(Cairo)",
    "Cairo_Citadel",
    "Temple_of_Derr",
    "Aquarium_Grotto_Garden",
    "Great Hypostyle Hall of Karnak",
    "49_Zainab_Khatun_house",
    "Qaed_Ibrahim_Mosque",
    "45_Hapi_The_Scribe",
    "9_Box_ofthe_Holy Quran",
    "21_A_silo",
    "Red_Pyramid",
    "Dendera_Temple_complex",
    "Egyptian_National_Military_Museum",
    "Faiyum_Zoo",
    "bust of ramesses ii",
    "Giza_Zoo",
    "Tomb_of_Nefertari",
    "Statue of King Zoser",
    "Gayer-Anderson_Museum",
    "5_Greek_Statues",
    "Temple_of_Seti_I_in_Abydos",
    "Orman_Garden",
    "Temple_of_Khonsu_in_Karnak",
    "Muhammad_Ali_Mosque",
    "Saint_George_Church_in_Coptic_Cairo",
    "Deir_el-Bahari",
    "Khan Elkhalili",
    "Aswan_High_Dam",
    "27_Khedive_Ismail",
    "Mosque_of_al-Maridani",
    "50_God_Nilus",
    "Sphinx_of_Memphis",
    "Sakakini_Palace",
    "Wadi_el_Gemal_National_Park",
    "Citadel_of_Qaitbay",
    "Pyramid_of_Nyuserre_Ini",
    "Khayrbak_Mosque",
    "Madrasah_of_Al-Nasir_Muhammad",
    "The Great Temple of Ramesses II",
    "Mohammed Ali Mosque in cairo citadel",
    "3_Hassan_Fathi",
    "City_of_the_dead_(Cairo)",
    "Al-Ashraf_Mosque",
    "26_Mamluk_Lamps",
    "Alexandria_Zoo",
    "Bibliotheca_Alexandrina",
    "Pompey's_Pillar,_Alexandria",
    "Esna_Temple",
    "White_Monastery",
    "Ibn Tulun Mosque",
    "46_Thoth",
    "44_Miller",
    "Al-Qurn",
    "Corniche_(Alexandria)",
    "Kiosk_of_Trajan_in_Philae",
    "KV17",
    "42_Baker",
    "Kom_el-Shoqafa",
    "Ramesseum",
    "Sabil_of_Abd_al-Rahman_Katkhuda",
    "Abu_el-Abbas_el-Mursi_Mosque",
    "Ras_Muhammad",
    "Cairo Tower",
    "Baron_Empain_Palace",
    "Bagawat",
    "Osireion",
    "Luxor_Temple",
    "Hatshepsut Temple",
    "Qasr_Qarun",
    "Islamic_Cairo",
    "Akhenaten"
]